frontend:
  origins: https://pei-cheng-yu.github.io

jwt:
  secret: ${JWT_SECRET}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://google/recipe
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${INSTANCE_CONNECTION_NAME}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create